# model settings
model = dict(
    type='GUPNet',
    backbone=dict(
        type='DLANet',
        depth=34,
        in_channels=3,
        norm_cfg=dict(type='BN'),
        init_cfg=dict(
            type='Pretrained',
            checkpoint='http://dl.yf.io/dla/models/imagenet/dla34-ba72cf86.pth'
        )),
    neck=dict(
        type='DLAUpsample_V2',
        channels=[64, 128, 256, 512],
        start_level = 2,
        scales = [1, 2, 4, 8],
        norm_cfg=dict(type='BN'),
        use_dcn=False), 
    bbox_head=dict(
        type='GUPHead',
        num_classes=10,
        norm_cfg=None,
        in_channels=None,
        stacked_convs=0,
        feat_channels=66,
        use_direction_classifier=False,
        diff_rad_by_sin=False,
        dir_offset=0,
        strides=None,
        pred_attrs=False,
        pred_velo=False,
        group_reg_dims=(2, 2, 2, 2, 6, 24),  #offset_2d, size_2d, depth, offset_3d, size_3d, heading, up_point, low_point, x3d
        cls_branch=(256, ),
        reg_branch=((256, ),  
                    (256, ), 
                    (256, ), 
                    (256, ), 
                    (256, ), 
                    (256, )),
        dir_branch=(),
        attr_branch=(),
        bbox_code_size=7,
        bbox_coder=dict(type='GUPCoder'),
        loss_cls=dict(type='GaussianFocalLoss', loss_weight=1.0),
        loss_offset2d = dict(type='L1Loss', loss_weight=1.0),
        loss_offset3d = dict(type='L1Loss', loss_weight=1.0),
        loss_size2d = dict(type='L1Loss', loss_weight=1.0),
        loss_size3d = dict(type='UncertainL1Loss', loss_weight=1.4142, alpha=1/1.4142),
        loss_depth = dict(type='UncertainL1Loss', loss_weight=1.4142, alpha=1/1.4142),
        loss_angle_bin = dict(type='CrossEntropyLoss', loss_weight=1.0),
        loss_angle_res = dict(type='L1Loss', loss_weight=1.0),
        conv_bias=True,
        dcn_on_last_conv=False),
    train_cfg=None,
    test_cfg=dict(
        topK=50, 
        local_maximum_kernel=3, 
        max_per_img=50,
        use_rotate_nms=True,
        nms_across_levels=False,
        min_bbox_size=0,
        nms_thr=0.8))